### ISSUE TITLE
Don't consider backup as failed with an app without backup script

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/borg_ynh#100]
### Describe the bug

The backup is considered as "failed" in the log mails when an app don't has any backup script :
Warning: The application ssh_chroot_dir__2 has no backup script. This app won't be backuped.

### Expected behavior

Keep the warning in the log mails, but change the subject in "success" instead of "failed".

**Comment by zamentur** [comment]
I am not agree with that.
I think it's better to get an error than to believe you have a backup and finally no.
I think it's ssh_chroot_dir that should give a backup script.
