### ISSUE TITLE
Provide GUI for user control

### ISSUE THREAD

**Issue by lightnin** [YunoHost-Apps/borg_ynh#106]
After installing Borg Yunohost does not give the user the ability to view, change or update settings entered at install time. (For example - encryption passphrase, or remote servers.)

Ideally it should be possible to configure and update configurations for common backup scenarios (i.e. to remote server like Borgbase, or another yunhosted borg server) without needing to access the command line.

**Comment by zamentur** [comment]
The new config panel allow you to do that now. 
The passphrase is the only things that as not been added in the config panel for now.
