### ISSUE TITLE
list of apps to backup : all except "app1, app2"

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/borg_ynh#114]
Is it possible to add the possibility to backup all apps except a list of apps ?
My use case : I want to backup all apps, but I have one app that has no backup script (ssh_chroot_dir). So the emails send are always marked as failed.
I would like to be able to backup all apps except ssh_chroot_dir.
I know I could list all installed apps with "yunohost app setting borg apps", but this way it wouldn't include new apps, so I risk to forget to add a new app in the backup when I install it.
Same demand on restic : https://github.com/ashemsay/restic_ynh/issues/15

**Comment by xoddark** [comment]
What you want is ***exclude:*** ?
It exist and is indicated in config-panel :
```App list separated by comma. You can write 'all' to select all apps, even those installed after this borg app. You can also select all apps but some apps by writing 'exclude:' following by an app list separated by comma.```

PS: I had the same problem when I tried the app the first time 😉

**Comment by tomdereub** [comment]
That's it, perfect, thank you ! I've just discovered the config panel for this app at the same time, that's great.
I just tried a few syntax before finding the good one, wich is : 
![image](https://user-images.githubusercontent.com/16243499/150543953-ac63f6de-7e76-46c5-9ede-cf7c33618234.png)
