### ISSUE TITLE
borg : /etc/sudoers.d/borg is owned by uid 995, should be 0 ; TTY=unknown ; PWD=/ ; USER=root

### ISSUE THREAD

**Issue by xoddark** [YunoHost-Apps/borg_ynh#118]
### Describe the bug

After installing Borg Backup application (with webadmin) I received email with the content :
borg : /etc/sudoers.d/borg is owned by uid 995, should be 0 ; TTY=unknown ; PWD=/ ; USER=root ; 

Backup is not done, and borg service is not started.

### Context

- Hardware: *Dedicated server*
- YunoHost version: 4.3.6
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: borg_ynh version 1.1.16~ynh28

### Steps to reproduce

- *Install Borg Backup app (tested from webadmin)*
    Last version tested : 1.1.16~ynh28
   I have setup email to "always" in app configuration
- *wait email with problem*

File /etc/sudoers.d/borg is owned by user "borg" instead of be owned by root ?

### Expected behavior

*The application should work after installation*

**Comment by shukon** [comment]
I experienced the same thing on two VPS's and one local Yunohost.
`pkexec chown root:root /etc/sudoers /etc/sudoers.d -R` fixed it for me, though if it's the right solution.

**Comment by tituspijean** [comment]
Related issue on the forum: https://forum.yunohost.org/t/backup-yunohost-with-borg-to-synology/18857

**Comment by artybdrlt** [comment]
Same problem here! Will it be fixed in a future release?
