### ISSUE TITLE
How does prunning work?

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/borg_ynh#122]
Is Borg going to keep by default -`-keep-hourly 2 --keep-daily=7 --keep-weekly=8 --keep-monthly=12 `https://github.com/YunoHost-Apps/borg_ynh/blob/testing/conf/backup_method#L55 ?

Meaning multiple backups?

Because I do not see that on my server. I see 1 archive per app, and I should see multiple if there are multiple backups created, correct?

**Comment by alexAubin** [comment]
c.f. borg documentation : https://borgbackup.readthedocs.io/en/stable/usage/prune.html

**Comment by tio-trom** [comment]
So it is not done automatically by this ynh_borg app, one should do it manually via SSH? If so can anyone show me an example of how can be done for yunohost? `borg prune -v --list --keep-daily=7 --keep-weekly=4 --prefix='{hostname}-' /path/to/repo` This is the borg documentation, but I am unsure what to replace the `hostname` and `/path/to/repo` with. I found ynh documentarion for borg for other things but not for this. Thanks

**Comment by tio-trom** [comment]
Ok it seems to keep versions of files.

**Comment by Cantello** [comment]
What did you use as `hostname`? If I don't use it, only one of the app backups is kept (wordpress in this case), all others were pruned. The backups have names like `_auto_appname_date_time` - any idea how borg can keep archives of the different apps?
