### ISSUE TITLE
The backup miserably failed to backup

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/borg_ynh#124]
### Describe the bug

That's the email I received.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2 
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*

Full logs here https://paste.yunohost.org/raw/lazotuyose

The thing is that I can see a Peertube archive being created...it is there in the borg repository.

**Comment by fflorent** [comment]
Woooh, there should not be any `.ts` (typescript) file in `storage/streaming-playlists/hls/` folders which must only contain video files and playlists (m4a, mp4, etc.).

Does the problem still occurs? If the file named `/var/www/peertube/storage/streaming-playlists/hls/24b5ac81-6b5c-4a80-87b8-9f7aeb4885c9/0-007060.ts` exists, what does it contain?

**Comment by tio-trom** [comment]
Here is a more recent log https://paste.yunohost.org/raw/wuyikivode

Apparently there are other .ts files. I think they are for the live streaming? See https://github.com/Chocobozzz/PeerTube/issues/5164

**Comment by fflorent** [comment]
> Apparently there are other .ts files.

Oh I see! TS in that case means *Video Transport Stream*. Thanks for this information!

**Comment by tio-trom** [comment]
I also get this for Friendica - this is the log https://paste.yunohost.org/raw/ikiwewapiq
`2022-08-15 00:15:10,919: WARNING - mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `process` at row: 0`

Friendica will take a while to backup and the database will change in the meantime in the process. Probably that's why it fails...is there a way to put these big apps in maintenance mode via this Borg script? Like put them in maintenance then do the backup.
