### ISSUE TITLE
Question : why using backports version of borg ?

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost-Apps/borg_ynh#18]
Out of curiosity, if there is any particular required feature.

**Comment by nicofrand** [comment]
Hi,

I found the answer in the code: https://github.com/YunoHost-Apps/borg_ynh/blob/master/scripts/install#L35.

Borg 1.1 is needed and it's only available in backports: https://packages.debian.org/stretch-backports/borgbackup.

**Comment by JocelynDelalande** [comment]
The reason of that dependance (feature ?) is not explicited.

**Comment by keomabrun** [comment]
From the Debian changelog, it seems that the backports version has only one security fix (introduced in v`1.1.9-1`).

https://metadata.ftp-master.debian.org/changelogs/main/b/borgbackup/borgbackup_1.1.9-2~bpo9+1_changelog
stretch v=`1.0.9-1`, stretch-backport v=`1.1.9-2`

I don't see why we need the backports here.

**Comment by JocelynDelalande** [comment]
@keomabrun erhh… There is much more differences between 1.0.9 and 1.1.9 according the changelog (not necessarily Debian patches, but upstream release features/fixes)

**Comment by keomabrun** [comment]
Sorry, you are right, I wasn't precise. There is only one critical difference to me that could justify the use of backports, that is the security fix. If the new features and patches are the reason why we use backports, I believe there should be justifications about it.

**Comment by zamentur** [comment]
I just remember why. It's because borgserver_ynh use --storage-quota option. This option is available only with a borg >=1.1.x ...

Repo are made differently between borg 1.0.x and borg 1.1.x i have choose to avoid a migration by going directly on borg 1.1.x format.

**Comment by JocelynDelalande** [comment]
Makes sense, thanks :-)
