### ISSUE TITLE
Allow to chose the repository path.

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/borg_ynh#20]
Hi,

thanks a lot for this script, I do hope I'll be able to make it work as expected and finally be able to backup my data.

I am using borgbase.com as a provider (instead of using a "server B" width borgserver_ynh installed). They provide a repo path like `user@user.repo.borgbase.com:repo`.

To be able to instantiate the creation I had to edit this line: and replace the `~/backup/` by `~/repo/`.

It would be great if the user could select its own path (like for the server name etc.) during the installation.

**Comment by zamentur** [comment]
Have you tried with ssh://user@user.repo.borgbase.com/~/repo/ ?

"~/backup/" is hardcoded cause the goals is to simplify as possible. I can probably put a hidden question in manifest to ask for the directory. It will be possible to define it with cli but not with webadmin.

Note: I work on a core integration of borg repo. So this app is not my big priority (it should be replaced by the new core features)

**Comment by nicofrand** [comment]
Well, now it seems to work, I would have bet it did not.

Here is a log though, `:repo` seems to mean `./repo` which is different from `~/repo` :

> The repository at location ssh://user@user.repo.borgbase.com/~/repo was previously located at ssh://user@user.repo.borgbase.com/./repo

> "~/backup/" is hardcoded cause the goals is to simplify as possible. I can probably put a hidden question in manifest to ask for the directory. It will be possible to define it with cli but not with webadmin.

This would be a great first step while the core integration arrives. I'll do a PR once I have found how to hide a question in the manifest.

**Comment by nicofrand** [comment]
I edited the ticket to only keep the repository path selection.

**Comment by fflorent** [comment]
I exactly had the same issue (also using borgbase). The hidden option would be highly appreciated :).

Also thanks for this app!

Florent

**Comment by nicofrand** [comment]
Hi @zamentur,

can you explain what you mean by "hidden option" please? I only see optional fields (except passwords but uhh): https://yunohost.org/#/packaging_apps_manifest_en.

Thanks in advance

**Comment by zamentur** [comment]
Fixed in #71

**Comment by nicofrand** [comment]
Thanks for the fix!

For any one wondering how to use the fix, you'll need to set your repo URL in the settings with `yunohost app setting repository "ssh://user@user.repo.location.com/~/path"`.

**Comment by fflorent** [comment]
> Thanks for the fix!
> 
> For any one wondering how to use the fix, you'll need to set your repo URL in the settings with `yunohost app setting repository "ssh://user@user.repo.location.com/~/path"`.

Thanks. There are some typo, the correct command is: 

```
yunohost app setting borg repository -v "ssh://user@user.repo.location.com/~/path"
```
