### ISSUE TITLE
Feature Request: Backup Nextcloud data

### ISSUE THREAD

**Issue by BCITMike** [YunoHost-Apps/borg_ynh#27]
I just did a reinstall of the borg app for yunohost and (luckily) realized that the Nextcloud data isn't actually getting backed up!  I thought the main point of borg backup for yunohost was being able to do large, frequent data backups?

I think that another case will need to be added to backup-with-borg.j2 that for Nextcloud, it does it twice, once with `backup_core_only` set or not set. Probably need to add that to configuration questions during install.

**Comment by zamentur** [comment]
In which version of yunohost are you ?

**Comment by zamentur** [comment]
I need to know if other person have this issue in recent version of yunohost ?

**Comment by zamentur** [comment]
I close this issue as it seems not anymore relevant
