### ISSUE TITLE
feature request: send one backup on multiple locations

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/borg_ynh#31]
It could be cool to do the backup once (I mean, all the work borg does before sending the backup to the destination) and send it to two (or more) different locations. For example, you can do a backup on a local hard disk and on a distant location.

**Comment by zamentur** [comment]
Backup with borg in YunoHost work like this:

1. Collect all files to backup by activating backup script (of yunohost and apps) (eventually make a dump)
2. Evaluate Size of all of this
3. Run the backup method (in this case borg), at this step, borg check remote "chunks" and send missing chunks .

This last step is dependent of the remote borg server (so borg can't precalculate for 2 servers).

About the phase number 1&2, this shouldn't be so long. But i may be wrong... If i am right you just need to install several borg_ynh app to manage all backup politics you need.

If i am wrong, please tell me how many times take the first step, and how it is bad for your use case.

**Comment by zamentur** [comment]
Note: it's possible to hack borg_ynh to send to 2 destinations with the same shedule task, but i discourage it. What if the first step fail, if you keep separate your backup is made locally or remotely if no you have no backup...

https://forum.yunohost.org/t/borg-backup-local-et-distants/6617/6?u=ljf

**Comment by tomdereub** [comment]
Ok, so it was just a bad idea.
