### ISSUE TITLE
Possibility to exclude/include nextcloud data from backup

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/borg_ynh#39]
As I evoked in [this topic on the forum](https://forum.yunohost.org/t/borg-backup-exclude-nextcloud-contents-and-get-noticed-if-backup-failed/10918), I recently discovered that my server hadn't been backed up for quite a while, because of a lack of space in the target server.

I'm trying to achieve two things to avoid this problem:
 - avoid backing up nextcloud data
 - getting some warnings on backup failures

I believe the first point can be achieved by fiddling around with the list of directories that borg is backing up, but I don't want to break the way borg_ynh makes it easy to add/remove some apps to the backup. Anyone has some advice on a good way to do that?
Also would be very grateful for suggestions on how to achieve the second point.

Thanks a lot for any advice and for this great app.

**Comment by zamentur** [comment]
Now you can have some warning if you have properly configured email on servera and serverb and check email send to first ynh created account (or redirect it).

**Comment by zamentur** [comment]
About avoiding to backup big data you can avoid it like this:

```
yunohost app setting nextcloud do_not_backup_data -v 1
```
Warning: this option applies for all your next backlup with all methods of any kind...
