### ISSUE TITLE
borg fails due to bad app listing

### ISSUE THREAD

**Issue by hieronymousch** [YunoHost-Apps/borg_ynh#42]
yunohost app list --installed -b | grep id: | cut -d: -f2 gives errors on latest version of yunohost (specifically for the -b parameter)

should read
yunohost app list | grep id: | cut -d: -f2

**Comment by eauchat** [comment]
I'm having the same issue. Since last yunohost update, apps were not backed up anymore.

I fixed it temporarily patching the file `/usr/local/bin/backup-with-borg`, according to the suggestion by @hieronymousch.
Now I guess my change will simply be replaced by next update containing fixed issue.
