### ISSUE TITLE
Yunohost diagnosis reports borg service status to be dead

### ISSUE THREAD

**Issue by eauchat** [YunoHost-Apps/borg_ynh#53]
Maybe I configured something wrong, but in my yunohost server, ynh diagnosis is raising errors saying that borg service is dead.

From what I understand, it makes sense that the service is dead, since it's starting only when it's making a backup.
It would be really nice indeed to know when backups are failing, but maybe the yunohost diagnosis should behave differently for borg_ynh service than other services. Maybe it should consider "dead" status to be ok, and raise an error if the status of the service is "failed".

But maybe I misunderstood something. Or I can imagine that it's not trivial to implement.

**Comment by zamentur** [comment]
I have just add in testing --test_status="systemctl show $app.service -p ActiveState --value | grep -v failed"

So it should fix this situation, dead state and inactive state seems ok indeed
