### ISSUE TITLE
Passphrase problem...

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/borg_ynh#54]
Hello,

When I do this command
`BORG_RSH="ssh -i /root/.ssh/id_borg_ed25519 -oStrictHostKeyChecking=yes " borg list servera@host.serverb:~/backup`

as expected, it asks me the passphrase but when I write it, it doesn't work. I first thought it I made a mistake so I went to check in this file 
`sudo nano /etc/yunohost/hooks.d/backup_method/05-borg_app`
and BORG_PASSPHRASE="xxxxx"
xxxxx is exactly what I wrote when the passphrase was requested.

Where am I wrong?
What should I do?

**Comment by KvL159** [comment]
I think I have similar issue, I used the following command :

 `ssh -i /root/.ssh/id_borg_ed25519 -v servera@host.serverb.dmn`

It first tried to use SSH key to login and then asks for a user password, which from my understanding doesn't have a password.

The password that we define during setup is to encrypt the backup before upload and the remote server doesn't access this password, right ?

It seem I'm not able to SSH the remote server (with borg server), any suggestions?

**Comment by Thatoo** [comment]
I have solved my problem thanks to Mamie in here https://forum.yunohost.org/t/passphrase-problem-with-borg-backup-app-for-yunohost/12863/2
