### ISSUE TITLE
prune options when several same applications delete backup 

### ISSUE THREAD

**Issue by espritlibre** [YunoHost-Apps/borg_ynh#56]
Hello,

I have several wordpress apps install on my server

When i check backup, at the end of it, i saw that some wordpress backup archive are missing

If you have more that 2 wordpress application (or other applications with the same name), when the prune hourly is execute (just after your backup), one of the archive is delete

For example
Backup works for

- wordpress
- wordpress__1
- wordpress__2

But when the backup of the wordpress__2 is done the wordpress__1 is prune.

https://github.com/YunoHost-Apps/borg_ynh/blob/07114d1b27621dab88bd52e04029bf186591d153/conf/backup_method.j2#L47

For the moment i disable the prune, i don't know if it's a bug of borg which ignore the __ in the name of archive and how can i modify prune to ignore that

**Comment by zamentur** [comment]
Fixed in #71
