### ISSUE TITLE
backup-with-borg automatically starts after server restart

### ISSUE THREAD

**Issue by deckname** [YunoHost-Apps/borg_ynh#60]
Nov 19 11:22:27 ... systemd[1]: Started Run backup borg regularly.
Nov 19 11:22:30 ... systemd[1]: Starting Run backup borg...
then the backup-with-borg routine starts

I restarted to confirm this happens every time: 
Nov 19 12:01:37 ... systemd[1]: Started Run backup borg regularly.
Nov 19 12:01:40 ...  systemd[1]: Starting Run backup borg...
then the backup-with-borg routine starts

I have it set to backup daily. With two restarts the app will do 3 backups today.

**Comment by alexAubin** [comment]
ping @zamentur : could it be that it's due to https://github.com/YunoHost-Apps/borg_ynh/blob/testing/conf/systemd.service#L12 ?

**Comment by zamentur** [comment]
Fixed in #71
