### ISSUE TITLE
doesn't work after upgrade from 1.1.10~ynh6 to 1.1.13~ynh2

### ISSUE THREAD

**Issue by deckname** [YunoHost-Apps/borg_ynh#64]
When I upgrade the app from 1.1.10\~ynh6 to 1.1.13\~ynh2, it doesn't do automatic backup. I think that it does run, but somehow it doesn't create the backups on the specified server like before. 
I am not using the corresponding backup app on the server that is used for storage but rather I manually configured the user and certificates, maybe something changed there?

**Comment by zamentur** [comment]
Have you solved your issues ?

**Comment by deckname** [comment]
No I haven't, but I reinstalled and I am trying to get that working.
