### ISSUE TITLE
Add an option to backup the yunohost.multimedia repository

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/borg_ynh#67]
I'm using the yunohost.multimedia repository as the main place where I store my personal data (it's easier to mount yunohost.multimedia as an encrypted partition than the whole /home folder), and borg to make my backups. It would be nice to be able to say to borg to save the yunohost.multimedia folder then.

**Comment by zamentur** [comment]
A PR is in progress about this issue https://github.com/YunoHost/yunohost/pull/1179

**Comment by alexAubin** [comment]
Closing as PR got merged
