### ISSUE TITLE
Support request: app keys / paths and other info. 

### ISSUE THREAD

**Issue by utzer** [YunoHost-Apps/borg_ynh#72]
Hello, 
this is not an issue I think, but more a request for support, but some of this could be enhanced. 

With `yunohost app setting borg -h` I get this output:
```
usage: yunohost app setting app key [-h] [-v VALUE] [-d]

Set or get an app setting value

positional arguments:
  app                   App ID
  key                   Key to get/set

optional arguments:
  -h, --help            show this help message and exit
  -v VALUE, --value VALUE
                        Value to set
  -d, --delete          Delete the key
```

But it seems to be impossible to get a list of the keys. 

I am currently wondering where borg gets the host information from, meaning which is the path of the SSH-config file it uses. I would like to check why the backup seems to work as per journalctl output, but the remote repo does not contain current backups. 

part of ls from remote repo:
```
drwxr-xr-x  1 user user    0 Nov 17 23:10 auto_borg_17_11_20_23:09/
drwxr-xr-x  1 user user    0 Nov 18 00:00 auto_borg_18_11_20_00:00/
drwxr-xr-x  1 user user    0 Nov 19 00:00 auto_borg_19_11_20_00:00/
drwxr-xr-x  1 user user    0 Nov 20 00:00 auto_borg_20_11_20_00:00/
drwxr-xr-x  1 user user    0 Nov 21 00:00 auto_borg_21_11_20_00:00/
```
Part of the journalctl output:
```
Mar 10 00:00:20 mail.example.com backup-with-borg[3832]: ls: cannot access '/etc/yunohost/hooks.d/backup/': No such file or directory
Mar 10 00:00:21 mail.example.com backup-with-borg[3832]: Creating a backup archive from the collected files...
Mar 10 00:00:22 mail.example.com backup-with-borg[3832]: Remote: Debian GNU/Linux 10
Mar 10 00:00:23 mail.example.com backup-with-borg[3832]: A repository already exists at ssh://hostname@correct.domain.example.com/~/backup.
Mar 10 00:01:38 mail.example.com backup-with-borg[3832]: Backup created
Mar 10 00:01:38 mail.example.com backup-with-borg[3832]: name: auto_data
Mar 10 00:01:38 mail.example.com backup-with-borg[3832]: results:
Mar 10 00:01:38 mail.example.com backup-with-borg[3832]:   apps:
Mar 10 00:01:38 mail.example.com backup-with-borg[3832]:   system:
Mar 10 00:01:38 mail.example.com backup-with-borg[3832]:     data_home: Success
Mar 10 00:01:38 mail.example.com backup-with-borg[3832]:     data_mail: Success
```
This looks good, but no idea where the backup goes to. 

It seems that at some point borg switched the repo path from `hostname:/volume1/shared/backup/some_name` to `hostname:~/backup/some_name`, to the later one it does not have permission to write a backup, but it still seems it does to so so. 

No I would like to look at all the config keys of the borg app and don't know how to figure out which keys are available.

**Comment by utzer** [comment]
Added some more info above. 

I am thinking about simply removing the app and adding it again and configuring it again. There is no helpful backup anyway it seems.

**Comment by zamentur** [comment]
Settings of apps are in /etc/yunohost/apps/*/settings.yml

**Comment by zamentur** [comment]
I close this ticket as you get your answer about settings location. For support help, prefer ask for on forum.yunohost.org (you can log on with your github account if prefered).
