### ISSUE TITLE
New install not working

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/borg_ynh#73]
Hello!

I just got a new VPS for storing my backup, where I installed yunohost followed by borgbackup app.
Then, on my old yunohost server I just installed the borg app.

I followed the given instructions in the README.md file :-)

Then I type the following commands and retrieve an error:

```
# SRV=backupuser@mybackupserverip:~/backup
# BORG_RSH="ssh -i /root/.ssh/id_borg_ed25519 -oStrictHostKeyChecking=yes " borg list $SRV
Connection closed by remote host. Is borg working on the server?
```

Just to be sure, I have my public/private keys on my old server to backup, and I gave this public key while installing borgserver on my new server storing the backups.

I have absolutely no idea is that's a ssh or borg issue.

Léo

**Comment by zamentur** [comment]
> I just got a new VPS for storing my backup, where I installed yunohost followed by borgbackup app.
> Then, on my old yunohost server I just installed the borg app.

Normally, the order to install this app is:

1. Install borg_ynh on your old yunohost server
2. Get the public key generated received by email or with `yunohost app setting borg public_key`
3. Install borgserver_ynh (and give the public key generated by borg_ynh)

SO you can't install the server before the client...
