### ISSUE TITLE
[security] BORG_PASSPHRASE is not removed when sharing logs

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/borg_ynh#87]
When a backup fails and we share logs with yunopaste, the BORG_PASSPHRASE is output in clear.

It would be worth to remove it (replace with some dummy password).

Also could be worth to also anonymize the distant repo:

![image](https://user-images.githubusercontent.com/371705/117941498-704be900-b30a-11eb-9e93-45395b315bb2.png)

Thanks!

**Comment by zamentur** [comment]
It has been fixed in unstable ynh version, will be available in next YNH version
https://github.com/YunoHost/yunohost/commit/dbe5e51ef134889ba385d84b08a69c249daa9c5e
