### ISSUE TITLE
Failed to start Run backup borg

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/borg_ynh#95]
### Describe the bug

> Failed to start Run backup borg

> borg.service: Failed with result 'exit-code'

*A clear and concise description of what the bug is.*

from log below

**/usr/local/bin/backup-with-borg: line 83: syntax error near unexpected token `fi'**

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 4.2.7 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

- Using, or trying to install package version/branch:
- If upgrading, current package version: **version: 1.1.16~ynh21** (latest upgrade)

### Steps to reproduce
- upgrade borg from server
- borg backup daily job worked fine untill latest upgrade
- I've not changed settings after upgrading 

### Expected behavior

borg systemctl service executed without errors

### Logs

Manually start borg service (I had seen borg failed in web interface)

`systemctl start borg.service`

 borg.service - Run backup borg
   Loaded: loaded (/etc/systemd/system/borg.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-08-19 05:56:57 BST; 1min 16s ago
  Process: 1581 ExecStart=/usr/bin/sudo /usr/local/bin/backup-with-borg borg (code=exited, status=2)
 Main PID: 1581 (code=exited, status=2)

Aug 19 05:56:56 domain.tld sudo[5577]: pam_unix(sudo:session): session closed for user root
Aug 19 05:56:56 domain.tld sudo[5579]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/yunohost app setting borg mailalert
Aug 19 05:56:56 domain.tld sudo[5579]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 19 05:56:57 domain.tld sudo[5579]: pam_unix(sudo:session): session closed for user root
Aug 19 05:56:57 domain.tld sudo[1581]: /usr/local/bin/backup-with-borg: line 83: syntax error near unexpected token `fi'

Aug 19 05:56:57 domain.tld sudo[1581]: /usr/local/bin/backup-with-borg: line 83: `fi'

Aug 19 05:56:57 domain.tld sudo[1581]: pam_unix(sudo:session): session closed for user root
Aug 19 05:56:57 domain.tld systemd[1]: borg.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 19 05:56:57 domain.tld systemd[1]: borg.service: Failed with result 'exit-code'.
Aug 19 05:56:57 domain.tld systemd[1]: Failed to start Run backup borg.

**Thanks**.

**Comment by TheNomad11** [comment]
I noticed the same issue today. After a reboot, Borg was running again. Let's wait and see how the next backup during the night will work

**Comment by TheNomad11** [comment]
The same thing happened. Borg kept running until the end of the backup process during the night, then failed to restart, the same syntax error as above:

Excerpt:

(....)

```
Aug 22 03:29:51 sudo[25150]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/test ! -f /etc/yunohost/apps/wordpress/scripts/backup
Aug 22 03:29:51 sudo[25150]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 03:29:51 sudo[25150]: pam_unix(sudo:session): session closed for user root
Aug 22 03:29:51 sudo[25152]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/yunohost backup create -n auto_wordpress --method borg_app --apps wordpress
Aug 22 03:29:51 sudo[25152]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 03:30:34 sudo[25152]: pam_unix(sudo:session): session closed for user root
Aug 22 03:30:34 sudo[25862]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/yunohost app setting borg repository
Aug 22 03:30:34 sudo[25862]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 03:30:34 sudo[25862]: pam_unix(sudo:session): session closed for user root
Aug 22 03:30:34 sudo[25864]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/yunohost app setting borg mailalert
Aug 22 03:30:34 sudo[25864]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 22 03:30:34 sudo[25864]: pam_unix(sudo:session): session closed for user root
Aug 22 03:30:34 sudo[9848]: /usr/local/bin/backup-with-borg: Zeile 83: Syntaxfehler beim unerwarteten Wort `fi'
Aug 22 03:30:34 sudo[9848]: /usr/local/bin/backup-with-borg: Zeile 83: `fi'
Aug 22 03:30:34 sudo[9848]: pam_unix(sudo:session): session closed for user root
Aug 22 03:30:35 systemd[1]: borg.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 22 03:30:35 systemd[1]: borg.service: Failed with result 'exit-code'.
Aug 22 03:30:35 systemd[1]: Failed to start Run backup borg.

```

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost-Apps/borg_ynh/commit/64358b3309c6ed03066e4d8c15eb5e29aeb6aab4 in `~ynh22`
